//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SearchEngine
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SearchEngineEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SearchEngineEntities2 object using the connection string found in the 'SearchEngineEntities2' section of the application configuration file.
        /// </summary>
        public SearchEngineEntities2() : base("name=SearchEngineEntities2", "SearchEngineEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SearchEngineEntities2 object.
        /// </summary>
        public SearchEngineEntities2(string connectionString) : base(connectionString, "SearchEngineEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SearchEngineEntities2 object.
        /// </summary>
        public SearchEngineEntities2(EntityConnection connection) : base(connection, "SearchEngineEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FolderType> FolderTypes
        {
            get
            {
                if ((_FolderTypes == null))
                {
                    _FolderTypes = base.CreateObjectSet<FolderType>("FolderTypes");
                }
                return _FolderTypes;
            }
        }
        private ObjectSet<FolderType> _FolderTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SingleFile> SingleFiles
        {
            get
            {
                if ((_SingleFiles == null))
                {
                    _SingleFiles = base.CreateObjectSet<SingleFile>("SingleFiles");
                }
                return _SingleFiles;
            }
        }
        private ObjectSet<SingleFile> _SingleFiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PluralDictionary> PluralDictionaries
        {
            get
            {
                if ((_PluralDictionaries == null))
                {
                    _PluralDictionaries = base.CreateObjectSet<PluralDictionary>("PluralDictionaries");
                }
                return _PluralDictionaries;
            }
        }
        private ObjectSet<PluralDictionary> _PluralDictionaries;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FolderTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFolderTypes(FolderType folderType)
        {
            base.AddObject("FolderTypes", folderType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SingleFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSingleFiles(SingleFile singleFile)
        {
            base.AddObject("SingleFiles", singleFile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PluralDictionaries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPluralDictionaries(PluralDictionary pluralDictionary)
        {
            base.AddObject("PluralDictionaries", pluralDictionary);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SearchEngineModel", Name="FolderType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FolderType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FolderType object.
        /// </summary>
        /// <param name="folderID">Initial value of the FolderID property.</param>
        /// <param name="folderExactLocation">Initial value of the FolderExactLocation property.</param>
        /// <param name="folderName">Initial value of the FolderName property.</param>
        /// <param name="lastEntry">Initial value of the LastEntry property.</param>
        /// <param name="fileSizeLimit">Initial value of the FileSizeLimit property.</param>
        /// <param name="nestedFolderRead">Initial value of the NestedFolderRead property.</param>
        /// <param name="searchingText">Initial value of the SearchingText property.</param>
        /// <param name="successfullyCreated">Initial value of the SuccessfullyCreated property.</param>
        public static FolderType CreateFolderType(global::System.Int64 folderID, global::System.String folderExactLocation, global::System.String folderName, global::System.DateTime lastEntry, global::System.Int32 fileSizeLimit, global::System.Boolean nestedFolderRead, global::System.String searchingText, global::System.Boolean successfullyCreated)
        {
            FolderType folderType = new FolderType();
            folderType.FolderID = folderID;
            folderType.FolderExactLocation = folderExactLocation;
            folderType.FolderName = folderName;
            folderType.LastEntry = lastEntry;
            folderType.FileSizeLimit = fileSizeLimit;
            folderType.NestedFolderRead = nestedFolderRead;
            folderType.SearchingText = searchingText;
            folderType.SuccessfullyCreated = successfullyCreated;
            return folderType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FolderID
        {
            get
            {
                return _FolderID;
            }
            set
            {
                if (_FolderID != value)
                {
                    OnFolderIDChanging(value);
                    ReportPropertyChanging("FolderID");
                    _FolderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FolderID");
                    OnFolderIDChanged();
                }
            }
        }
        private global::System.Int64 _FolderID;
        partial void OnFolderIDChanging(global::System.Int64 value);
        partial void OnFolderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FolderExactLocation
        {
            get
            {
                return _FolderExactLocation;
            }
            set
            {
                OnFolderExactLocationChanging(value);
                ReportPropertyChanging("FolderExactLocation");
                _FolderExactLocation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FolderExactLocation");
                OnFolderExactLocationChanged();
            }
        }
        private global::System.String _FolderExactLocation;
        partial void OnFolderExactLocationChanging(global::System.String value);
        partial void OnFolderExactLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FolderName
        {
            get
            {
                return _FolderName;
            }
            set
            {
                OnFolderNameChanging(value);
                ReportPropertyChanging("FolderName");
                _FolderName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FolderName");
                OnFolderNameChanged();
            }
        }
        private global::System.String _FolderName;
        partial void OnFolderNameChanging(global::System.String value);
        partial void OnFolderNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastEntry
        {
            get
            {
                return _LastEntry;
            }
            set
            {
                OnLastEntryChanging(value);
                ReportPropertyChanging("LastEntry");
                _LastEntry = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastEntry");
                OnLastEntryChanged();
            }
        }
        private global::System.DateTime _LastEntry;
        partial void OnLastEntryChanging(global::System.DateTime value);
        partial void OnLastEntryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExcludeExt
        {
            get
            {
                return _ExcludeExt;
            }
            set
            {
                OnExcludeExtChanging(value);
                ReportPropertyChanging("ExcludeExt");
                _ExcludeExt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExcludeExt");
                OnExcludeExtChanged();
            }
        }
        private global::System.String _ExcludeExt;
        partial void OnExcludeExtChanging(global::System.String value);
        partial void OnExcludeExtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IncludeExt
        {
            get
            {
                return _IncludeExt;
            }
            set
            {
                OnIncludeExtChanging(value);
                ReportPropertyChanging("IncludeExt");
                _IncludeExt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IncludeExt");
                OnIncludeExtChanged();
            }
        }
        private global::System.String _IncludeExt;
        partial void OnIncludeExtChanging(global::System.String value);
        partial void OnIncludeExtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FileSizeLimit
        {
            get
            {
                return _FileSizeLimit;
            }
            set
            {
                OnFileSizeLimitChanging(value);
                ReportPropertyChanging("FileSizeLimit");
                _FileSizeLimit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FileSizeLimit");
                OnFileSizeLimitChanged();
            }
        }
        private global::System.Int32 _FileSizeLimit;
        partial void OnFileSizeLimitChanging(global::System.Int32 value);
        partial void OnFileSizeLimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StartingLimit
        {
            get
            {
                return _StartingLimit;
            }
            set
            {
                OnStartingLimitChanging(value);
                ReportPropertyChanging("StartingLimit");
                _StartingLimit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartingLimit");
                OnStartingLimitChanged();
            }
        }
        private Nullable<global::System.Decimal> _StartingLimit;
        partial void OnStartingLimitChanging(Nullable<global::System.Decimal> value);
        partial void OnStartingLimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EndingLimit
        {
            get
            {
                return _EndingLimit;
            }
            set
            {
                OnEndingLimitChanging(value);
                ReportPropertyChanging("EndingLimit");
                _EndingLimit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndingLimit");
                OnEndingLimitChanged();
            }
        }
        private Nullable<global::System.Decimal> _EndingLimit;
        partial void OnEndingLimitChanging(Nullable<global::System.Decimal> value);
        partial void OnEndingLimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean NestedFolderRead
        {
            get
            {
                return _NestedFolderRead;
            }
            set
            {
                OnNestedFolderReadChanging(value);
                ReportPropertyChanging("NestedFolderRead");
                _NestedFolderRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NestedFolderRead");
                OnNestedFolderReadChanged();
            }
        }
        private global::System.Boolean _NestedFolderRead;
        partial void OnNestedFolderReadChanging(global::System.Boolean value);
        partial void OnNestedFolderReadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Parent
        {
            get
            {
                return _Parent;
            }
            set
            {
                OnParentChanging(value);
                ReportPropertyChanging("Parent");
                _Parent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Parent");
                OnParentChanged();
            }
        }
        private Nullable<global::System.Int64> _Parent;
        partial void OnParentChanging(Nullable<global::System.Int64> value);
        partial void OnParentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SearchingText
        {
            get
            {
                return _SearchingText;
            }
            set
            {
                OnSearchingTextChanging(value);
                ReportPropertyChanging("SearchingText");
                _SearchingText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SearchingText");
                OnSearchingTextChanged();
            }
        }
        private global::System.String _SearchingText;
        partial void OnSearchingTextChanging(global::System.String value);
        partial void OnSearchingTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SuccessfullyCreated
        {
            get
            {
                return _SuccessfullyCreated;
            }
            set
            {
                OnSuccessfullyCreatedChanging(value);
                ReportPropertyChanging("SuccessfullyCreated");
                _SuccessfullyCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuccessfullyCreated");
                OnSuccessfullyCreatedChanged();
            }
        }
        private global::System.Boolean _SuccessfullyCreated;
        partial void OnSuccessfullyCreatedChanging(global::System.Boolean value);
        partial void OnSuccessfullyCreatedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SearchEngineModel", Name="PluralDictionary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PluralDictionary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PluralDictionary object.
        /// </summary>
        /// <param name="single">Initial value of the Single property.</param>
        /// <param name="plural">Initial value of the Plural property.</param>
        public static PluralDictionary CreatePluralDictionary(global::System.String single, global::System.String plural)
        {
            PluralDictionary pluralDictionary = new PluralDictionary();
            pluralDictionary.Single = single;
            pluralDictionary.Plural = plural;
            return pluralDictionary;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Single
        {
            get
            {
                return _Single;
            }
            set
            {
                if (_Single != value)
                {
                    OnSingleChanging(value);
                    ReportPropertyChanging("Single");
                    _Single = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Single");
                    OnSingleChanged();
                }
            }
        }
        private global::System.String _Single;
        partial void OnSingleChanging(global::System.String value);
        partial void OnSingleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Plural
        {
            get
            {
                return _Plural;
            }
            set
            {
                OnPluralChanging(value);
                ReportPropertyChanging("Plural");
                _Plural = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Plural");
                OnPluralChanged();
            }
        }
        private global::System.String _Plural;
        partial void OnPluralChanging(global::System.String value);
        partial void OnPluralChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SearchEngineModel", Name="SingleFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SingleFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SingleFile object.
        /// </summary>
        /// <param name="singleFileID">Initial value of the SingleFileID property.</param>
        /// <param name="folderID">Initial value of the FolderID property.</param>
        /// <param name="isNoContent">Initial value of the IsNoContent property.</param>
        /// <param name="accessDate">Initial value of the AccessDate property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
        /// <param name="sizeInBytes">Initial value of the SizeInBytes property.</param>
        /// <param name="lastEntryDateTime">Initial value of the LastEntryDateTime property.</param>
        public static SingleFile CreateSingleFile(global::System.Int64 singleFileID, global::System.Int64 folderID, global::System.Boolean isNoContent, global::System.DateTime accessDate, global::System.DateTime createdDate, global::System.DateTime modifiedDate, global::System.Decimal sizeInBytes, global::System.DateTime lastEntryDateTime)
        {
            SingleFile singleFile = new SingleFile();
            singleFile.SingleFileID = singleFileID;
            singleFile.FolderID = folderID;
            singleFile.IsNoContent = isNoContent;
            singleFile.AccessDate = accessDate;
            singleFile.CreatedDate = createdDate;
            singleFile.ModifiedDate = modifiedDate;
            singleFile.SizeInBytes = sizeInBytes;
            singleFile.LastEntryDateTime = lastEntryDateTime;
            return singleFile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SingleFileID
        {
            get
            {
                return _SingleFileID;
            }
            set
            {
                if (_SingleFileID != value)
                {
                    OnSingleFileIDChanging(value);
                    ReportPropertyChanging("SingleFileID");
                    _SingleFileID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SingleFileID");
                    OnSingleFileIDChanged();
                }
            }
        }
        private global::System.Int64 _SingleFileID;
        partial void OnSingleFileIDChanging(global::System.Int64 value);
        partial void OnSingleFileIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FolderID
        {
            get
            {
                return _FolderID;
            }
            set
            {
                OnFolderIDChanging(value);
                ReportPropertyChanging("FolderID");
                _FolderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FolderID");
                OnFolderIDChanged();
            }
        }
        private global::System.Int64 _FolderID;
        partial void OnFolderIDChanging(global::System.Int64 value);
        partial void OnFolderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content1
        {
            get
            {
                return _Content1;
            }
            set
            {
                OnContent1Changing(value);
                ReportPropertyChanging("Content1");
                _Content1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content1");
                OnContent1Changed();
            }
        }
        private global::System.String _Content1;
        partial void OnContent1Changing(global::System.String value);
        partial void OnContent1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content2
        {
            get
            {
                return _Content2;
            }
            set
            {
                OnContent2Changing(value);
                ReportPropertyChanging("Content2");
                _Content2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content2");
                OnContent2Changed();
            }
        }
        private global::System.String _Content2;
        partial void OnContent2Changing(global::System.String value);
        partial void OnContent2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNoContent
        {
            get
            {
                return _IsNoContent;
            }
            set
            {
                OnIsNoContentChanging(value);
                ReportPropertyChanging("IsNoContent");
                _IsNoContent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNoContent");
                OnIsNoContentChanged();
            }
        }
        private global::System.Boolean _IsNoContent;
        partial void OnIsNoContentChanging(global::System.Boolean value);
        partial void OnIsNoContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AccessDate
        {
            get
            {
                return _AccessDate;
            }
            set
            {
                OnAccessDateChanging(value);
                ReportPropertyChanging("AccessDate");
                _AccessDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccessDate");
                OnAccessDateChanged();
            }
        }
        private global::System.DateTime _AccessDate;
        partial void OnAccessDateChanging(global::System.DateTime value);
        partial void OnAccessDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MD5
        {
            get
            {
                return _MD5;
            }
            set
            {
                OnMD5Changing(value);
                ReportPropertyChanging("MD5");
                _MD5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MD5");
                OnMD5Changed();
            }
        }
        private global::System.String _MD5;
        partial void OnMD5Changing(global::System.String value);
        partial void OnMD5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SizeInBytes
        {
            get
            {
                return _SizeInBytes;
            }
            set
            {
                OnSizeInBytesChanging(value);
                ReportPropertyChanging("SizeInBytes");
                _SizeInBytes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SizeInBytes");
                OnSizeInBytesChanged();
            }
        }
        private global::System.Decimal _SizeInBytes;
        partial void OnSizeInBytesChanging(global::System.Decimal value);
        partial void OnSizeInBytesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastEntryDateTime
        {
            get
            {
                return _LastEntryDateTime;
            }
            set
            {
                OnLastEntryDateTimeChanging(value);
                ReportPropertyChanging("LastEntryDateTime");
                _LastEntryDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastEntryDateTime");
                OnLastEntryDateTimeChanged();
            }
        }
        private global::System.DateTime _LastEntryDateTime;
        partial void OnLastEntryDateTimeChanging(global::System.DateTime value);
        partial void OnLastEntryDateTimeChanged();

        #endregion

    
    }

    #endregion

    
}
